mode: docker

server:
  base_url: api-gateway
  port: 8080

user_service:
  base_url: user-service
  port: 50051

auth_jwt_token:
  name: authify_token
  secret: 493TKVrB0r5vY0hqU3OI28iDQJKhWDkR37OXtgSn1tife3z
  max_age: 3600
  domain: host.docker.internal
  secure: false
  http_only: true
  path: '/'

redis:
  port: 6379
  address: host.docker.internal
  password: ''
  database_index: 0
