mode: production

server:
  base_url: 0.0.0.0 # ALB connect to EC2 in private subnet
  port: 80

user_service:
  base_url: 0.0.0.0
  port: 50051

auth_jwt_token:
  name: authify-token
  max_age: 3600
  secure: false
  http_only: true
  path: '/'
  secret: CHANGE_ME
  domain: CHANGE_ME

redis:
  port: 6379
  database_index: 0
  address: CHANGE_ME
