apiVersion: v1
kind: Service
metadata:
  name: api-gateway-clusterip
  namespace: inventory-management-system
spec:
  type: ClusterIP
  ports:
    - targetPort: 80
      port: 80
  selector:
    ims: api-gateway

---
apiVersion: v1
kind: Service
metadata:
  name: user-clusterip
  namespace: inventory-management-system
spec:
  type: ClusterIP
  ports:
    - targetPort: 50051
      port: 50051
  selector:
    ims: authentication
