apiVersion: v1
kind: PersistentVolume
metadata:
  name: authify-pv-user
  namespace: authify
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 500Mi
  # manually creating PV to match the StorageClass, ensures that this PV is considered for
  # PVCs that request this StorageClass
  storageClassName: authify-storage-class
  # for dev, mounting a directory from local computer's filesystem on Node into Pod
  hostPath:
    path: /Users/leonlow/persistent_volume/user-postgres
  # keeps the PV around for manual cleanup if the PVC is deleted
  persistentVolumeReclaimPolicy: Retain
