apiVersion: v1
kind: Secret
metadata:
  name: user-secret
  namespace: authify
type: Opaque
data:
  POSTGRES_USER: dXNlci1wb3N0Z3Jlcw== # base64 encoded 'user-postgres'
  POSTGRES_PASSWORD: cGFzc3dvcmQ= # base64 encoded 'password'

  # base64 encoded 'user-headless-service'
  POSTGRES_HOST: dXNlci1oZWFkbGVzcy1zZXJ2aWNl
